#!/bin/bash
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#

#
# Test syncing with out-of-order bundle delivery
#
#
#


if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

if [ -z "$TEST_DURATION" ]; then
    TEST_DURATION=30
fi

. $ROOT/test/testlib.sh
. $ROOT/test/config.sh

if [ -z "$ENABLE_ION" ]; then
    echo "Bionet not configured with ION. Skipping test"
    exit 3
fi

UNIQUE=$$
RETVAL=0

function dirempty() {
    RC=0
    for dir in "$@"; do
        if [ `ls "$dir" | wc -l` -gt 0 ]; then
            RC=1
        fi
    done

    return $RC
}

function dir_not_empty() {
    ! dirempty "$@"
}

# We REALLY need to cleanup if we can
on_die()
{
    echo "Killing jobs: " `jobs -p`
    kill `jobs -p`
    killm
    exit 2
}
trap 'on_die' TERM INT

test_error()
{
    echo "Error running test: $@"

    echo "Killing jobs: " `jobs -p`
    kill `jobs -p`

    echo "Stopping ION Node 1..."
    ionstop -D ion1
    echo "Stopping ION Node 2..."
    ionstop -D ion2

    echo "Running killm"
    killm > /dev/null

    exit 1

}

YEAR=`date +%Y`
PREV_YEAR=$(($YEAR-1))
NEXT_YEAR=$(($YEAR+1))

### Setup
##################################################
ulimit -Sc unlimited

# Setup ION multi-node
export ION_NODE_LIST_DIR=$PWD

./clean
test_log "removed old DB file, and allowing bionet-data-manger to create schema"

### Start ION instances
##################################################

mkdir filecla
mkdir filecla/host1 filecla/host2 filecla/host2-delay

cat > ion1/host1.ionconfig <<ENDCFG
wmKey 1
sdrName ion1
configFlags 5
pathName ${PWD}/ion1
ENDCFG

cat > ion2/host2.ionconfig <<ENDCFG
wmKey 2
sdrName ion2
configFlags 5
pathName ${PWD}/ion2
ENDCFG

test_log "Starting ION node 1..."
ionstart -I ion1/host1.rc -D ion1
test_log "Starting ION node 2..."
ionstart -I ion2/host2.rc -D ion2

### Start Sync Receiver
##################################################

test_log "Starting ION sync receiver BDM"
ION_NODE_WDNAME=$PWD/ion2 $ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file sync-bdm.db --id sync-recv-$UNIQUE --no-resources --dtn-endpoint-id 'ipn:2.1' --dtn-sync-receiver  --debug --log-file=sync-recv.log &
RECVPID=$!

### Start Sync Sender
##################################################
test_log "starting ION sync sender BDM"
ION_NODE_WDNAME=$PWD/ion1 $ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file orig-bdm.db --id sync-send-$UNIQUE --filter "random-hab.$UNIQUE.*:*" --dtn-endpoint-id 'ipn:1.1' --sync-sender-config  bdm-sync-send.cfg --port 11111  --debug --log-file=sync-send.log &
SENDPID=$!

time_watch 60 grep -i "connected to bionet" sync-send.log || test_error "bdm didn't start"
sleep 5 # let the bdm come up before starting the HAB

$ROOT/data-manager/client/bdm-watcher/bdm-watcher -o bdm-client -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" \
	-r "sync-recv-$UNIQUE,sync-send-$UNIQUE/random-hab.$UNIQUE.*:*" \
	-n "sync-recv-$UNIQUE,sync-send-$UNIQUE/random-hab.$UNIQUE.*" \
	-h "sync-recv-$UNIQUE,sync-send-$UNIQUE/random-hab.$UNIQUE" \
	>| out.watch.bdm-sync &
WATCHPID=$!

test_log "starting random-hab"
$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
HABPID=$!

test_log "Generating data. Waiting for first bundle...."
time_watch 20 dir_not_empty filecla/host2-delay || test_error "First bundle never generated"

### SyncBundles are being generated.
test_log "Sync bundles being generated. Waiting a bit..."
sleep 10


test_log "killing random-hab"
kill $HABPID
wait $HABPID

test_log "Waiting for most data to sync"
sleep 10

test_log "Manually delivering bundles in (mostly) reverse order..."
bundle_cnt=0
while dir_not_empty filecla/host2-delay; do
    for bdl in `ls -t filecla/host2-delay`; do
        mv filecla/host2-delay/$bdl filecla/host2
	bundle_cnt=`expr $bundle_cnt + 1`
        sleep 1
    done
done

test_log "$bundle_cnt bundles delivered"
test_log "Waiting for all data to sync"
time_watch 120 dirempty filecla/host2 || (find filecla; test_error "Data didn't sync in time")
sleep 5

$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
test_log "killing the ION sync sender BDM"
kill $SENDPID
wait $SENDPID

test_log "getting data from TCP sync receiver BDM"

$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-sync

test_log "bplist, Node 1:"
(cd ion1 && bplist)
test_log "bplist, Node 2:"
(cd ion2 && bplist)

test_log "killing ION Sync Receive BDM"
kill $RECVPID
wait $RECVPID

kill $WATCHPID
wait $WATCHPID

test_log "bplist, Node 1:"
(cd ion1 && bplist)
test_log "bplist, Node 2:"
(cd ion2 && bplist)


# see what we got
(cd ion1 && bpstats)
(cd ion2 && bpstats)

# shut down ion processes
echo "Stopping ION Node 1..."
ionstop -D ion1
echo "Stopping ION Node 2..."
ionstop -D ion2
echo "Running killm"
killm > /dev/null

### Compare output files
##################################################
normalize_bdm_client out.random-hab > norm.random-hab

for x in bdm-orig bdm-sync watch.bdm-sync; do
    normalize_bdm_client out.$x > norm.$x
    if ! diff -q norm.random-hab norm.$x; then
	echo "ERROR: $x output differs from random-hab output:"
	#diff -u norm.random-hab norm.$x
	RETVAL=1
    else
	echo "$x output is identical to random-hab output, yay"
    fi
done

if ! diff -q out.bdm-orig out.bdm-sync; then
    echo "ERROR: Sync'd BDM output differs from Original:"
    #diff -u out.bdm-orig out.bdm-sync
    RETVAL=1
else
    echo "Sync'd BDM output is identical to original, yay"
fi

exit $RETVAL

