
include ../../Makefile.params

CFLAGS += -I .. -I ../../util


OBJS =                      \
    bip-read-from-peer.o    \
    bip-send-message.o      \


all: $(OBJS)

clean:
	rm -f $(OBJS)

test:

install:

.PHONY: all test install clean


