#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#

MAC=`perl -e 'if (\`uname -a\` =~ m/^Darwin/) { print "true" };'`
if $MAC; then
    echo "Skipping on OSX for now"
    exit 2
fi

UNIQUE=$$

if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi


echo starting Streamy HAB
$ROOT/hab/streamy/streamy-hab --id $UNIQUE &

STREAM="Streamy.$UNIQUE.incoming:incoming" 
for FILE in test-pattern-*; do
    rm -f incoming:incoming
    echo sending file $FILE to stream $STREAM
    $ROOT/client/stream/bionet-stream $STREAM < $FILE

    mv incoming:incoming out.$FILE
    if ! cmp  $FILE out.$FILE ; then
        echo "ERROR: $FILE differs from out.$FILE:"
        hd $FILE > hd.$FILE
        hd out.$FILE > hd.out.$FILE
        diff -u hd.$FILE hd.out.$FILE
	kill %1
        exit 1
    fi
    echo "files are identical, yay"
done

kill %1
wait
echo "stream transit successfull!"

