#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


export ROOT="$(pwd)/.."


TESTS=$@

. $ROOT/test/config.sh

ulimit -Sc unlimited

if [ -z "$TESTS" ]; then
    TESTS=$(ls -1d tests/* | sort)
fi

for TEST in $TESTS; do
    [ ! -d "$TEST" ] && continue

    echo
    echo "*** ${TEST}"
    echo -n "*** " && date

    if [ -x "$TEST/clean" ]; then
        pushd "$TEST" > /dev/null
        ./clean
        popd > /dev/null
    fi

done

exit 0

