#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


export ROOT="$(pwd)/.."

NUM_SKIPPED=0
NUM_PASSED=0
NUM_FAILED=0

TESTS=$@

if [ -z "$TESTS" ]; then
    TESTS=$(ls -1d tests/* | sort)
fi

for TEST in $TESTS; do
    [ ! -d "$TEST" ] && continue

    echo
    echo "*** ${TEST}"

    if [ ! -x "$TEST/run" ]; then
        echo "disabled, skipping"
        NUM_SKIPPED=$(($NUM_SKIPPED+1))
        continue
    fi

    pushd "$TEST" > /dev/null
    ./run
    if [ $? -eq 0 ]; then
        echo "TEST PASSED!"
        NUM_PASSED=$(($NUM_PASSED+1))
    else
        echo "TEST FAILED!"
        NUM_FAILED=$(($NUM_FAILED+1))
    fi
    popd > /dev/null
done

echo
echo "passed: $NUM_PASSED"
echo "failed: $NUM_FAILED"
echo "skipped: $NUM_SKIPPED"

if [ "$NUM_FAILED" = 0 ]; then
    exit 0
else
    exit 1
fi

