#!/bin/bash
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#
# This script lets you run one test over and over again until it fails or
# you stop it.
#
# Run from this directory, and specify the path(s)
# to the test directories to repeat
#

export ROOT="$(pwd)/.."

TESTS=$@

. $ROOT/test/config.sh

if [ -z "$TESTS" ]; then
    TESTS=$(ls -1d tests/* | sort)
fi


LOOP=0
while : ; do
    for TEST in $TESTS; do
	if [ -d "tests/$TEST".* ]; then
	    TEST=`echo tests/$TEST.*`
	    echo "$TEST"
	fi
        [ ! -d "$TEST" ] && continue

        echo
        echo "*** ${TEST} (Iteration $LOOP)"
        echo -n "*** "; date

        if [ ! -x "$TEST/run" ]; then
            echo "disabled, skipping"
            continue
        fi

        pushd "$TEST" > /dev/null
        ./run
	RC=$?
        if [ $RC -eq 0 ]; then
            echo "TEST PASSED!"
        elif [ $RC -eq $TEST_SKIP_CODE ]; then
            echo "test disabled itself, skipping"
        #elif [ $RC -eq $TEST_WARNING_CODE ]; then
        #    echo "test generated a warning"
        else
	    echo "*** ${TEST} (Iteration $LOOP) FAILED!"
            exit 1
        fi
        popd > /dev/null
    done
    sleep 1
    LOOP=`expr $LOOP + 1`
done

