#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#
# This script lets you run one test over and over again until it fails or
# you stop it.
#
# Run from this directory, and specify the path(s)
# to the test directories to repeat
#

export ROOT="$(pwd)/.."

TESTS=$@

if [ -z "$TESTS" ]; then
    TESTS=$(ls -1d tests/* | sort)
fi


while : ; do
    for TEST in $TESTS; do
        [ ! -d "$TEST" ] && continue

        echo
        echo "*** ${TEST}"

        echo -n "*** " && date

        if [ ! -x "$TEST/run" ]; then
            echo "disabled, skipping"
            NUM_SKIPPED=$(($NUM_SKIPPED+1))
            continue
        fi

        pushd "$TEST" > /dev/null
        ./run
        if [ $? -eq 0 ]; then
            echo "TEST PASSED!"
        else
            echo "TEST FAILED!"
            exit 1
        fi
        popd > /dev/null
    done
    sleep 1
done

