#!/usr/bin/python

# To use coffeepot client:
# First, change resource to appropriate address. Use correct Kill-A-Watt ID.
# Change username and password if desired ('command', -u and -p)
# To run, use bionet-warn client with command ./bionet-warn -c "examples/coffee-and-tea-pots-twitter"

on = { 'coffeepot' : False, 'teapot' : False }

def turn_off(x, name):
    global on
    if (x < 50 and on[name] == True):
        on[name] = False
        return 1
    return 0

def turn_on(x, name):
    global on
    if (x > 200 and on[name] == False):
        on[name] = True
	return 1
    return 0
            


warn = [
    {
    'resource': "Kill-A-Watt.quick.1:Watts", 
    'compare': lambda x: turn_off(x, 'coffeepot') > 0,
    'command': "./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Coffeepot is now ready. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.1:Watts", 
    'compare': lambda x: turn_on(x, 'coffeepot') > 0,
    'command': "./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Coffeepot is now ready. Coffeepot was just started. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.4:Watts", 
    'compare': lambda x: turn_off(x, 'teapot') > 0,
    'command': "./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Teapot is now ready. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.4:Watts", 
    'compare': lambda x: turn_on(x, 'teapot') > 0,
    'command': "./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Teapot was just started. $(fortune -n 100)\""
    }
]


