#!/usr/bin/python

# To use coffeepot client:
# First, change resource to appropriate address. Use correct Kill-A-Watt ID.
# Change sender and receiver emails if desired ('command', -s and -r)
# To run, use bionet-warn client with command ./bionet-warn -c "examples/coffeepot"

on = { 'coffeepot-mouseroom' : False, 'teapot-mouseroom' : False }

def turn_off(x, name):
    global on
    if (x < 50 and on[name] == True):
        on[name] = False
        return 1
    return 0

def turn_on(x, name):
    global on
    if (x > 200 and on[name] == False):
        on[name] = True
	return 1
    return 0
            


warn = [
    {
    'resource': "Kill-A-Watt.quick.1:Watts", 
    'compare': lambda x: turn_off(x, 'coffeepot-mouseroom') > 0,
    'command': "./examples/teapotmail -s coffeepot-mouseroom@bioserve.colorado.edu -r ilana.bellowe@colorado.edu \"Coffeepot is now ready. Come get some delicious coffee while it's nice and warm :) !\"; ./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Coffeepot is now ready. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.1:Watts", 
    'compare': lambda x: turn_on(x, 'coffeepot-mouseroom') > 0,
    'command': "./examples/teapotmail -s coffeepot-mouseroom@bioserve.colorado.edu -r ilana.bellowe@colorado.edu \"Coffeepot was just started. Coffee coming soon. :) !\"; ./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Coffeepot is now ready. Coffeepot was just started. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.4:Watts", 
    'compare': lambda x: turn_off(x, 'teapot-mouseroom') > 0,
    'command': "./examples/teapotmail -s teapot-mouseroom@bioserve.colorado.edu -r teapot@bioserve.colorado.edu \"Teapot is now ready. Come get a cup of tea, while it's still hot!\"; ./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Teapot is now ready. $(fortune -n 100)\""
    },

    {
    'resource': "Kill-A-Watt.quick.4:Watts", 
    'compare': lambda x: turn_on(x, 'teapot-mouseroom') > 0,
    'command': "./examples/teapotmail -s teapot-mouseroom@bioserve.colorado.edu -r teapot@bioserve.colorado.edu \"Teapot was just started. Water is warming up!\"; ./examples/teapottwitter -u \"Killawatt1217\" -p \"killawatt1\" -m \"Teapot was just started. $(fortune -n 100)\""
    }
]


