#!/usr/bin/python
import twitter
import logging
import optparse

logger = logging.getLogger("Twitter Teapot")
logger.setLevel(logging.INFO)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
ch.setFormatter(formatter)
logger.addHandler(ch)

parser = optparse.OptionParser()
parser.add_option("-u", "--user", dest="user", help="Choose the username of the twitter account", metavar = "USER")
parser.add_option("-p", "--password", dest="password", help="Type the password for the twitter account", metavar = "PASS")
parser.add_option("-m", "--message", dest="message", default="Warn client is sending a message", help="Type the message you want twitter to read", metavar="MESSAGE")

(options, args) = parser.parse_args()


def TwitterIt(u, p, message):
    api = twitter.Api(username=u, password=p)
    try:
        status = api.PostUpdate(message)
        logger.debug("%s just posted %s" % (status.user.name, status.text))
    except UnicodeDecodeError:
        logger.warning("Your message could not be encoded. Perhaps it contains non-ASCII characters? Try explicitly specifying the encoding with the --encoding flag.")
    except:
        logger.warning("Couldn't connect, check network, username and password.")

message = options.message[:135]
TwitterIt(options.user, options.password, message)
