#!/bin/bash

TEST_DURATION=30

UNIQUE=$$

if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

echo starting random-hab
$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bionet-watcher --max-delay 1 >| out.random-hab &

echo starting two bionet-watchers
$ROOT/client/watcher/bionet-watcher --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" >| out.watcher.0 &
$ROOT/client/watcher/bionet-watcher --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" >| out.watcher.1 &

sleep $TEST_DURATION

kill %1
sleep 2  # to let the clients notice

kill %2
kill %3


if ! diff -q out.watcher.0 out.watcher.1; then
    echo "ERROR: watcher outputs differ:"
    diff -u out.watcher.0 out.watcher.1
    exit 1
fi
echo "watcher outputs are identical, yay"

if ! diff -q out.watcher.0 out.random-hab; then
    echo "ERROR: watcher output differs from random-hab output:"
    diff -u out.random-hab out.watcher.0
    exit 1
fi
echo "watcher outputs are identical to random-hab output, yay"

