#!/bin/bash

if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

UNIQUE=$$


echo starting Streamy HAB
$ROOT/hab/streamy/streamy-hab --id $UNIQUE &

for FILE in test-pattern-*; do
    STREAM="Streamy.$UNIQUE.outgoing:$FILE" 
    echo reading file $FILE via stream $STREAM
    $ROOT/client/stream/bionet-stream $STREAM >| out.$FILE &
    sleep 5
    kill %2
    wait %2

    if ! cmp  $FILE out.$FILE ; then
        echo "ERROR: $FILE differs from out.$FILE:"
        hd $FILE > hd.$FILE
        hd out.$FILE > hd.out.$FILE
        diff -u hd.$FILE hd.out.$FILE
        exit 1
    fi
    echo "files are identical, yay"
done


kill %1
echo "stream transit successfull!"

