#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

UNIQUE=$$

. $ROOT/test/testlib.sh

BW_LIMIT=2 #KB/sec



echo starting Streamy HAB
$ROOT/hab/streamy/streamy-hab --id $UNIQUE --bandwidth-limit $BW_LIMIT &
SHABPID=$!

for FILE in test-pattern-*; do
    STREAM="Streamy.$UNIQUE.outgoing:$FILE" 
    echo reading file $FILE via stream $STREAM
    $ROOT/client/stream/bionet-stream $STREAM >| out.$FILE &
    SCLIENTPID=$!

    size=`stat -c%s $FILE`
    delay=`expr $size / \( 1000 \* $BW_LIMIT \) + 5`

    if ! time_wait $SCLIENTPID $delay; then
        kill $SCLIENTPID
        wait $SCLIENTPID
    fi

    if ! cmp  $FILE out.$FILE ; then
        echo "ERROR: $FILE differs from out.$FILE:"
        hexdump $FILE > hd.$FILE
        hexdump out.$FILE > hd.out.$FILE
        #diff -u hd.$FILE hd.out.$FILE
	kill %1
        exit 1
    fi
    echo "files are identical, yay"
done


kill %1
echo "stream transit successfull!"

