#!/usr/bin/python


# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.

# This library is free software. You can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as 
# published by the Free Software Foundation, version 2.1 of the License.
# This library is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
# Lesser General Public License for more details. A copy of the GNU 
# Lesser General Public License v 2.1 can be found in the file named 
# "COPYING.LESSER".  You should have received a copy of the GNU Lesser 
# General Public License along with this library; if not, write to the 
# Free Software Foundation, Inc., 
# 51 Franklin Street, Fifth Floor, 
# Boston, MA 02110-1301 USA.
 
# You may contact the Automation Group at:
# bionet@bioserve.colorado.edu
 
# Dr. Kevin Gifford
# University of Colorado
# Engineering Center, ECAE 1B08
# Boulder, CO 80309
 
# Because BioNet was developed at a university, we ask that you provide
# attribution to the BioNet authors in any redistribution, modification, 
# work, or article based on this library.
 
# You may contribute modifications or suggestions to the University of
# Colorado for the purpose of discussing and improving this software.
# Before your modifications are incorporated into the master version 
# distributed by the University of Colorado, we must have a contributor
# license agreement on file from each contributor. If you wish to supply
# the University with your modifications, please join our mailing list.
# Instructions can be found on our website at 
# http://bioserve.colorado.edu/developers-corner.


import optparse
import logging
from select import select
from hab import *

# initialize the Python logger
logger = logging.getLogger("Bionet Commandable PyHAB")
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
ch.setFormatter(formatter)
logger.addHandler(ch)

# parse options 
parser = optparse.OptionParser()
parser.add_option("-i", "--id", dest="id", default=None,
                  help="Hab-ID. Defaults to the hostname.")

(options, args) = parser.parse_args()

def cb_set_resource(resource, value):
    resource.set(value)
    hp = HabPublisher(resource.node().hab())
    hp.reportDatapoints(resource.node())


bionet_log_use_default_handler(None)

hab = Hab("commandable", options.id)
hp = HabPublisher(hab)
hp.setResourceCallback = cb_set_resource
hp.connect()

node = Node(hab, "set-me")
hab.add(node)

for data_type in range(BIONET_RESOURCE_DATA_TYPE_BINARY,BIONET_RESOURCE_DATA_TYPE_STRING+1):
    resource = Resource(hab.node("set-me"), 
                        data_type, BIONET_RESOURCE_FLAVOR_PARAMETER, 
                        "commandable-" + bionet_resource_data_type_to_string(data_type))
    hab.node("set-me").add(resource)

hp.reportNode(hp.hab.node("set-me"))

while(1):
    hp.read(None)
