######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 13 12:53:30 2007
######################################################################

unix: QMAKE_CC = gcc
unix: QMAKE_CXX = g++

INC_DIR = /tmp/include
LIB_DIR = /tmp/lib

TEMPLATE = lib
TARGET =
DESTDIR =

libs.path = $$LIB_DIR
libs.files = bionet-qt4.a
INSTALLS += libs

headers.path = $$INC_DIR
headers.files = $$HEADERS
INSTALLS += headers

