
include ../../Makefile.params

CFLAGS += -I .. -I ../.. -I ../../info

OBJS =                          \
    free-event.o                \
    free-peer.o                 \
    peer-add-unicast-address.o  \


all: $(OBJS)

clean:
	rm -f $(OBJS)

.PHONY: all clean

