#!/bin/bash
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

. ${ROOT}/test/testlib.sh

if [ -z "$TEST_DURATION" ]; then
    TEST_DURATION=30
fi

UNIQUE=$$
SYNCUNIQUE=${HOSTNAME//\./-}
RETVAL=0


YEAR=`date +%Y`
PREV_YEAR=$(($YEAR-1))
NEXT_YEAR=$(($YEAR+1))

#Generate core files on error
ulimit -Sc unlimited

echo "making DB file"
rm -f orig-bdm.db sync-bdm.db
sqlite3 orig-bdm.db < $ROOT/data-manager/server/schema
cp orig-bdm.db sync-bdm.db

test_log "Starting test-pattern-hab recorder"
rm -f testpattern.in
$ROOT/client/watcher/bionet-watcher --output-mode 'test-pattern' > testpattern.in &
TPPID=$!

test_log "starting TCP sync receiver BDM"
rm -f bdm.log.b
$ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file sync-bdm.db --id sync-recv-$SYNCUNIQUE --no-resources --tcp-sync-receiver --debug --log-file=bdm.log.b &
RECVPID=$!
echo " -> $ROOT/data-manager/server/bionet-data-manager $RECVPID"

test_log "starting TCP sync sender BDM"
rm -f bdm.log.a
$ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --file orig-bdm.db --id sync-send-$SYNCUNIQUE --filter "random-hab.$UNIQUE.*:*" --sync-sender-config $ROOT/test/tests/110.bdmsync-over-tcp-random-to-bdm-to-bdm/test.cfg --port 11111 --debug --log-file=bdm.log.a &
SENDPID=$!
echo " ->  $ROOT/data-manager/server/bionet-data-manager $SENDPID"
sleep 6 # let the bdm come up before starting the HAB


WATCHCMD="$ROOT/data-manager/client/bdm-watcher/bdm-watcher --output-mode 'bdm-client' -T '$PREV_YEAR-01-01 00:00:00' -t '$NEXT_YEAR-12-31 12:59:59' -r 'sync-recv-$SYNCUNIQUE,sync-send-$SYNCUNIQUE/random-hab.$UNIQUE.*:*'"

echo "bdm-watcher args: $WATCHCMD"


test_log "no datapoints generated, starting bdm-watcher.0"
eval "$WATCHCMD >| out.bdm-watcher.0 &"
WPID0=$!

test_log "starting random-hab"
$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bdm-client --max-delay 1 >| out.random-hab &
HABPID=$!

sleep `expr $TEST_DURATION / 2`

test_log "some datapoints generated, starting bdm-watcher.1"
eval "$WATCHCMD >| out.bdm-watcher.1 &"
WPID1=$!

sleep `expr $TEST_DURATION / 2`

test_log "all datapoints generated. Killing random-hab"
kill $HABPID
wait $HABPID

# Let the BDM commit the last info to disk
sleep 30

#Use BDM-Client to get the datapoints specifically from the sync-sender
$ROOT/data-manager/scripts/bdm-client.py -o chrono -s localhost -p 11111 -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" >| out.bdm-orig
test_log "test run complete. killing the TCP sync sender BDM"
kill $SENDPID
wait $SENDPID

test_log "all datapoints generated. Killing  bdm-watcher.0 and bdm-watcher.1"
kill $WPID0
kill $WPID1
wait $WPID0
wait $WPID1

test_log "all datapoints generated. Sync-sender stopped. Starting bdm-watcher.2"
eval "$WATCHCMD >| out.bdm-watcher.2 & "
WPID2=$!

sleep 30
kill $WPID2
wait $WPID2

test_log "Killing  bdm-watcher.2"

test_log "killing BDM"
kill $RECVPID
wait $RECVPID

kill $TPPID
wait $TPPID

for i in out.bdm-watcher.0 out.bdm-watcher.1 out.bdm-watcher.2 out.bdm-orig; do
    sort $i > $i.sorted
    if ! diff -q out.random-hab $i.sorted; then
	echo "ERROR: $i output differs from random-hab output:"
	diff -u out.random-hab $i.sorted
	RETVAL=1
    else
	echo "$i output same as random-hab output"
    fi
done

if [ $RETVAL -eq 0 ] ; then
    echo "All outputs checkout. Yeah!"
fi

exit $RETVAL

