#!/bin/sh
#
# Copyright (C) 2004-2008, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G and NNC06CB40C.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of GNU General Public License version 2, as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


BSTREAM="../../client/stream/bionet-stream"


NAG="bionet-base"

if [ "$1" = "--nag" ]; then
    shift
    NAG="$1"
    shift
fi


# for sox
BIOSERVE_AUDIO_FORMAT_SOX="-t raw -r 9600 -c 1 -s -w"


# for aplay
BIOSERVE_AUDIO_FORMAT_APLAY="-t raw -r 9600 -c 1 -f S16_LE"



# play the filtered stream
$BSTREAM --nag $NAG "$1" | ./lowpass.sh | $BSTREAM --nag $NAG "$2"

# save via sox
#$BSTREAM --nag $NAG "$1" | sox $BIOSERVE_AUDIO_FORMAT_SOX - "$2"


# play via aplay
#$BSTREAM --nag $NAG "$1" | aplay -D plug:dmix $BIOSERVE_AUDIO_FORMAT_APLAY

