#!/bin/sh
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


BSTREAM="../../client/stream/bionet-stream"


NAG="bionet-base"

if [ "$1" = "--nag" ]; then
    shift
    NAG="$1"
    shift
fi


# for sox
BIOSERVE_AUDIO_FORMAT_SOX="-t raw -r 9600 -c 1 -s -w"


# for aplay
BIOSERVE_AUDIO_FORMAT_APLAY="-t raw -r 9600 -c 1 -f S16_LE"



# play the filtered stream
$BSTREAM --nag $NAG "$1" | ./lowpass.sh | $BSTREAM --nag $NAG "$2"

# save via sox
#$BSTREAM --nag $NAG "$1" | sox $BIOSERVE_AUDIO_FORMAT_SOX - "$2"


# play via aplay
#$BSTREAM --nag $NAG "$1" | aplay -D plug:dmix $BIOSERVE_AUDIO_FORMAT_APLAY

