#!/bin/sh

#
# Copyright (C) 2008-2009, Regents of the University of Colorado.
#



#set -e
#set -x

BSTREAM="../../client/stream/bionet-stream"
#BSTREAM="bionet-stream"

LOWPASS="./lowpass.sh"
#LOWPASS="lowpass.sh"

NAG="bionet.colorado.edu"


STETHOSCOPE_STREAM="$1"
if [ -z "$STETHOSCOPE_STREAM" ]; then
    echo "usage: play-stethoscope STETHOSCOPE_STREAM"
    echo available streams:
    $BSTREAM --nag $NAG
    exit 1
fi


$BSTREAM --nag $NAG $STETHOSCOPE_STREAM | $LOWPASS | aplay -t raw -r 9600 -c 1 -f S16_LE

