#!/bin/sh
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


#set -e
#set -x

BSTREAM="../../client/stream/bionet-stream"
#BSTREAM="bionet-stream"

LOWPASS="./lowpass.sh"
#LOWPASS="lowpass.sh"

NAG="bionet.colorado.edu"


STETHOSCOPE_STREAM="$1"
if [ -z "$STETHOSCOPE_STREAM" ]; then
    echo "usage: play-stethoscope STETHOSCOPE_STREAM"
    echo available streams:
    $BSTREAM 
    exit 1
fi

echo "$BSTREAM $STETHOSCOPE_STREAM"
$BSTREAM $STETHOSCOPE_STREAM | $LOWPASS | aplay -t raw -r 9600 -c 1 -f S16_LE

