/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDM_Sync_Ack_H_
#define	_BDM_Sync_Ack_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BDM_Sync_Ack {
	BDM_Sync_Ack_error	= -1,
	BDM_Sync_Ack_datapointAck	= 0,
	BDM_Sync_Ack_metadataAck	= 1
} e_BDM_Sync_Ack;

/* BDM-Sync-Ack */
typedef long	 BDM_Sync_Ack_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDM_Sync_Ack;
asn_struct_free_f BDM_Sync_Ack_free;
asn_struct_print_f BDM_Sync_Ack_print;
asn_constr_check_f BDM_Sync_Ack_constraint;
ber_type_decoder_f BDM_Sync_Ack_decode_ber;
der_type_encoder_f BDM_Sync_Ack_encode_der;
xer_type_decoder_f BDM_Sync_Ack_decode_xer;
xer_type_encoder_f BDM_Sync_Ack_encode_xer;
per_type_decoder_f BDM_Sync_Ack_decode_uper;
per_type_encoder_f BDM_Sync_Ack_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BDM_Sync_Ack_H_ */
