/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDM_Event_H_
#define	_BDM_Event_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralizedTime.h>
#include <NativeInteger.h>
#include "BDM-Event-Type.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BDM-Event */
typedef struct BDM_Event {
	GeneralizedTime_t	 timestamp;
	long	 entrySeq;
	BDM_Event_Type_t	 type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDM_Event_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDM_Event;

#ifdef __cplusplus
}
#endif

#endif	/* _BDM_Event_H_ */
