/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDM_HardwareAbstractor_H_
#define	_BDM_HardwareAbstractor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BDM_Node;
struct BDM_Event;

/* BDM-HardwareAbstractor */
typedef struct BDM_HardwareAbstractor {
	PrintableString_t	 type;
	PrintableString_t	 id;
	struct BDM_HardwareAbstractor__nodes {
		A_SEQUENCE_OF(struct BDM_Node) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nodes;
	struct BDM_HardwareAbstractor__events {
		A_SEQUENCE_OF(struct BDM_Event) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} events;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDM_HardwareAbstractor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDM_HardwareAbstractor;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BDM-Node.h"
#include "BDM-Event.h"

#endif	/* _BDM_HardwareAbstractor_H_ */
