/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDM_C2S_Message_H_
#define	_BDM_C2S_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResourceDatapointsQuery.h"
#include <PrintableString.h>
#include "BDMSendState.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BDM_C2S_Message_PR {
	BDM_C2S_Message_PR_NOTHING,	/* No components present */
	BDM_C2S_Message_PR_resourceDatapointsQuery,
	BDM_C2S_Message_PR_subscribeHab,
	BDM_C2S_Message_PR_subscribeNode,
	BDM_C2S_Message_PR_subscribeDatapoints,
	BDM_C2S_Message_PR_sendState
} BDM_C2S_Message_PR;

/* BDM-C2S-Message */
typedef struct BDM_C2S_Message {
	BDM_C2S_Message_PR present;
	union BDM_C2S_Message_u {
		ResourceDatapointsQuery_t	 resourceDatapointsQuery;
		PrintableString_t	 subscribeHab;
		PrintableString_t	 subscribeNode;
		PrintableString_t	 subscribeDatapoints;
		BDMSendState_t	 sendState;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDM_C2S_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDM_C2S_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _BDM_C2S_Message_H_ */
