/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#include <asn_internal.h>

#include "BDM-Sync-Message.h"

static asn_TYPE_member_t asn_MBR_BDM_Sync_Message_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BDM_Sync_Message, data),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BDM_Sync_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDM_Sync_Message, syncchannel),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"syncchannel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDM_Sync_Message, firstSeq),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"firstSeq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDM_Sync_Message, lastSeq),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lastSeq"
		},
};
static ber_tlv_tag_t asn_DEF_BDM_Sync_Message_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BDM_Sync_Message_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* data at 367 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* syncchannel at 368 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* firstSeq at 369 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* lastSeq at 371 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDM_Sync_Message_specs_1 = {
	sizeof(struct BDM_Sync_Message),
	offsetof(struct BDM_Sync_Message, _asn_ctx),
	asn_MAP_BDM_Sync_Message_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDM_Sync_Message = {
	"BDM-Sync-Message",
	"BDM-Sync-Message",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDM_Sync_Message_tags_1,
	sizeof(asn_DEF_BDM_Sync_Message_tags_1)
		/sizeof(asn_DEF_BDM_Sync_Message_tags_1[0]), /* 1 */
	asn_DEF_BDM_Sync_Message_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDM_Sync_Message_tags_1)
		/sizeof(asn_DEF_BDM_Sync_Message_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDM_Sync_Message_1,
	4,	/* Elements count */
	&asn_SPC_BDM_Sync_Message_specs_1	/* Additional specs */
};

