/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDM_Event_Type_H_
#define	_BDM_Event_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BDM_Event_Type {
	BDM_Event_Type_new	= 0,
	BDM_Event_Type_lost	= 1
} e_BDM_Event_Type;

/* BDM-Event-Type */
typedef long	 BDM_Event_Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDM_Event_Type;
asn_struct_free_f BDM_Event_Type_free;
asn_struct_print_f BDM_Event_Type_print;
asn_constr_check_f BDM_Event_Type_constraint;
ber_type_decoder_f BDM_Event_Type_decode_ber;
der_type_encoder_f BDM_Event_Type_encode_der;
xer_type_decoder_f BDM_Event_Type_decode_xer;
xer_type_encoder_f BDM_Event_Type_encode_xer;
per_type_decoder_f BDM_Event_Type_decode_uper;
per_type_encoder_f BDM_Event_Type_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BDM_Event_Type_H_ */
