/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDMLostNode_H_
#define	_BDMLostNode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <GeneralizedTime.h>
#include <PrintableString.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BDMLostNode */
typedef struct BDMLostNode {
	long	 entrySeq;
	GeneralizedTime_t	 timestamp;
	PrintableString_t	 bdmId;
	OCTET_STRING_t	 uid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDMLostNode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDMLostNode;

#ifdef __cplusplus
}
#endif

#endif	/* _BDMLostNode_H_ */
