/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#include <asn_internal.h>

#include "BDMResourceMetadata.h"

static asn_TYPE_member_t asn_MBR_BDMResourceMetadata_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, habType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"habType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, habId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"habId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, nodeId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nodeId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, nodeUid),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nodeUid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, resourceId),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"resourceId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, flavor),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResourceFlavor,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"flavor"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceMetadata, datatype),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResourceDataType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"datatype"
		},
};
static ber_tlv_tag_t asn_DEF_BDMResourceMetadata_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BDMResourceMetadata_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* habType at 114 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* habId at 115 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nodeId at 116 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* nodeUid at 117 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* resourceId at 118 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* flavor at 119 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* datatype at 121 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDMResourceMetadata_specs_1 = {
	sizeof(struct BDMResourceMetadata),
	offsetof(struct BDMResourceMetadata, _asn_ctx),
	asn_MAP_BDMResourceMetadata_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDMResourceMetadata = {
	"BDMResourceMetadata",
	"BDMResourceMetadata",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDMResourceMetadata_tags_1,
	sizeof(asn_DEF_BDMResourceMetadata_tags_1)
		/sizeof(asn_DEF_BDMResourceMetadata_tags_1[0]), /* 1 */
	asn_DEF_BDMResourceMetadata_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDMResourceMetadata_tags_1)
		/sizeof(asn_DEF_BDMResourceMetadata_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDMResourceMetadata_1,
	7,	/* Elements count */
	&asn_SPC_BDMResourceMetadata_specs_1	/* Additional specs */
};

