/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#ifndef	_BDMResourceMetadata_H_
#define	_BDMResourceMetadata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include "ResourceFlavor.h"
#include "ResourceDataType.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BDMResourceMetadata */
typedef struct BDMResourceMetadata {
	PrintableString_t	 bdmId;
	PrintableString_t	 habType;
	PrintableString_t	 habId;
	PrintableString_t	 nodeId;
	PrintableString_t	 resourceId;
	ResourceFlavor_t	 flavor;
	ResourceDataType_t	 datatype;
	long	 entrySeq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDMResourceMetadata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDMResourceMetadata;

#ifdef __cplusplus
}
#endif

#endif	/* _BDMResourceMetadata_H_ */
