/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#include <asn_internal.h>

#include "BDMResourceDatapoints.h"

static asn_TYPE_member_t asn_MBR_newDatapointsBDM_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Datapoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_newDatapointsBDM_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_newDatapointsBDM_specs_7 = {
	sizeof(struct newDatapointsBDM),
	offsetof(struct newDatapointsBDM, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_newDatapointsBDM_7 = {
	"newDatapointsBDM",
	"newDatapointsBDM",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_newDatapointsBDM_tags_7,
	sizeof(asn_DEF_newDatapointsBDM_tags_7)
		/sizeof(asn_DEF_newDatapointsBDM_tags_7[0]) - 1, /* 1 */
	asn_DEF_newDatapointsBDM_tags_7,	/* Same as above */
	sizeof(asn_DEF_newDatapointsBDM_tags_7)
		/sizeof(asn_DEF_newDatapointsBDM_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_newDatapointsBDM_7,
	1,	/* Single element */
	&asn_SPC_newDatapointsBDM_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BDMResourceDatapoints_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, bdmId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bdmId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, habType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"habType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, habId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"habId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, nodeId),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nodeId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, resourceId),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"resourceId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, newDatapointsBDM),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_newDatapointsBDM_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"newDatapointsBDM"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMResourceDatapoints, entrySeq),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"entrySeq"
		},
};
static ber_tlv_tag_t asn_DEF_BDMResourceDatapoints_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BDMResourceDatapoints_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bdmId at 136 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* habType at 137 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* habId at 138 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* nodeId at 139 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* resourceId at 140 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* newDatapointsBDM at 141 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* entrySeq at 143 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDMResourceDatapoints_specs_1 = {
	sizeof(struct BDMResourceDatapoints),
	offsetof(struct BDMResourceDatapoints, _asn_ctx),
	asn_MAP_BDMResourceDatapoints_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDMResourceDatapoints = {
	"BDMResourceDatapoints",
	"BDMResourceDatapoints",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDMResourceDatapoints_tags_1,
	sizeof(asn_DEF_BDMResourceDatapoints_tags_1)
		/sizeof(asn_DEF_BDMResourceDatapoints_tags_1[0]), /* 1 */
	asn_DEF_BDMResourceDatapoints_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDMResourceDatapoints_tags_1)
		/sizeof(asn_DEF_BDMResourceDatapoints_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDMResourceDatapoints_1,
	7,	/* Elements count */
	&asn_SPC_BDMResourceDatapoints_specs_1	/* Additional specs */
};

