/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#include <asn_internal.h>

#include "BDMRecord.h"

static asn_TYPE_member_t asn_MBR_syncDatapoints_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Datapoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_syncDatapoints_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_syncDatapoints_specs_4 = {
	sizeof(struct syncDatapoints),
	offsetof(struct syncDatapoints, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_syncDatapoints_4 = {
	"syncDatapoints",
	"syncDatapoints",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_syncDatapoints_tags_4,
	sizeof(asn_DEF_syncDatapoints_tags_4)
		/sizeof(asn_DEF_syncDatapoints_tags_4[0]) - 1, /* 1 */
	asn_DEF_syncDatapoints_tags_4,	/* Same as above */
	sizeof(asn_DEF_syncDatapoints_tags_4)
		/sizeof(asn_DEF_syncDatapoints_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_syncDatapoints_4,
	1,	/* Single element */
	&asn_SPC_syncDatapoints_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BDMRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BDMRecord, entryTimestamp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"entryTimestamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMRecord, resourceKey),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"resourceKey"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDMRecord, syncDatapoints),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_syncDatapoints_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"syncDatapoints"
		},
};
static ber_tlv_tag_t asn_DEF_BDMRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BDMRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* entryTimestamp at 83 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* resourceKey at 84 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* syncDatapoints at 86 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDMRecord_specs_1 = {
	sizeof(struct BDMRecord),
	offsetof(struct BDMRecord, _asn_ctx),
	asn_MAP_BDMRecord_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDMRecord = {
	"BDMRecord",
	"BDMRecord",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDMRecord_tags_1,
	sizeof(asn_DEF_BDMRecord_tags_1)
		/sizeof(asn_DEF_BDMRecord_tags_1[0]), /* 1 */
	asn_DEF_BDMRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDMRecord_tags_1)
		/sizeof(asn_DEF_BDMRecord_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDMRecord_1,
	3,	/* Elements count */
	&asn_SPC_BDMRecord_specs_1	/* Additional specs */
};

