/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_BDMSyncRecord_H_
#define	_BDMSyncRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResourceRecord;

/* BDMSyncRecord */
typedef struct BDMSyncRecord {
	PrintableString_t	 bdmID;
	struct BDMSyncRecord__syncResources {
		A_SEQUENCE_OF(struct ResourceRecord) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} syncResources;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDMSyncRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDMSyncRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ResourceRecord.h"

#endif	/* _BDMSyncRecord_H_ */
