/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#include <asn_internal.h>

#include "DataManager.h"

static asn_TYPE_member_t asn_MBR_hablist_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BDM_HardwareAbstractor,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_hablist_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_hablist_specs_3 = {
	sizeof(struct DataManager__hablist),
	offsetof(struct DataManager__hablist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_hablist_3 = {
	"hablist",
	"hablist",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_hablist_tags_3,
	sizeof(asn_DEF_hablist_tags_3)
		/sizeof(asn_DEF_hablist_tags_3[0]) - 1, /* 1 */
	asn_DEF_hablist_tags_3,	/* Same as above */
	sizeof(asn_DEF_hablist_tags_3)
		/sizeof(asn_DEF_hablist_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_hablist_3,
	1,	/* Single element */
	&asn_SPC_hablist_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DataManager_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataManager, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataManager, hablist),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_hablist_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hablist"
		},
};
static ber_tlv_tag_t asn_DEF_DataManager_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DataManager_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id at 338 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* hablist at 340 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DataManager_specs_1 = {
	sizeof(struct DataManager),
	offsetof(struct DataManager, _asn_ctx),
	asn_MAP_DataManager_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DataManager = {
	"DataManager",
	"DataManager",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DataManager_tags_1,
	sizeof(asn_DEF_DataManager_tags_1)
		/sizeof(asn_DEF_DataManager_tags_1[0]), /* 1 */
	asn_DEF_DataManager_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataManager_tags_1)
		/sizeof(asn_DEF_DataManager_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DataManager_1,
	2,	/* Elements count */
	&asn_SPC_DataManager_specs_1	/* Additional specs */
};

