/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#include <asn_internal.h>

#include "Datapoint.h"

static asn_TYPE_member_t asn_MBR_Datapoint_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Datapoint, value),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Value,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"value"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Datapoint, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timestamp"
		},
};
static ber_tlv_tag_t asn_DEF_Datapoint_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Datapoint_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* value at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* timestamp at 44 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Datapoint_specs_1 = {
	sizeof(struct Datapoint),
	offsetof(struct Datapoint, _asn_ctx),
	asn_MAP_Datapoint_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Datapoint = {
	"Datapoint",
	"Datapoint",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Datapoint_tags_1,
	sizeof(asn_DEF_Datapoint_tags_1)
		/sizeof(asn_DEF_Datapoint_tags_1[0]), /* 1 */
	asn_DEF_Datapoint_tags_1,	/* Same as above */
	sizeof(asn_DEF_Datapoint_tags_1)
		/sizeof(asn_DEF_Datapoint_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Datapoint_1,
	2,	/* Elements count */
	&asn_SPC_Datapoint_specs_1	/* Additional specs */
};

