/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_DataManager_H_
#define	_DataManager_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BDM_HardwareAbstractor;

/* DataManager */
typedef struct DataManager {
	PrintableString_t	 id;
	struct DataManager__hablist {
		A_SEQUENCE_OF(struct BDM_HardwareAbstractor) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} hablist;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataManager_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataManager;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BDM-HardwareAbstractor.h"

#endif	/* _DataManager_H_ */
