/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_H2C_Message_H_
#define	_H2C_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Node.h"
#include <PrintableString.h>
#include "ResourceMetadata.h"
#include "ResourceDatapoints.h"
#include "StreamData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum H2C_Message_PR {
	H2C_Message_PR_NOTHING,	/* No components present */
	H2C_Message_PR_newNode,
	H2C_Message_PR_lostNode,
	H2C_Message_PR_resourceMetadata,
	H2C_Message_PR_datapointsUpdate,
	H2C_Message_PR_streamData
} H2C_Message_PR;

/* H2C-Message */
typedef struct H2C_Message {
	H2C_Message_PR present;
	union H2C_Message_u {
		Node_t	 newNode;
		PrintableString_t	 lostNode;
		ResourceMetadata_t	 resourceMetadata;
		ResourceDatapoints_t	 datapointsUpdate;
		StreamData_t	 streamData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} H2C_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_H2C_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _H2C_Message_H_ */
