/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_HardwareAbstractor_H_
#define	_HardwareAbstractor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Node;

/* HardwareAbstractor */
typedef struct HardwareAbstractor {
	PrintableString_t	 type;
	PrintableString_t	 id;
	struct HardwareAbstractor__nodes {
		A_SEQUENCE_OF(struct Node) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nodes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HardwareAbstractor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HardwareAbstractor;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Node.h"

#endif	/* _HardwareAbstractor_H_ */
