/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_C2H_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_H2C_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BDM_C2S_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BDM_S2C_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BDM_Sync_Metadata_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BDM_Sync_Datapoints_Message;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module BionetProtocol0 in bionet-protocol-0.asn1 */
	&asn_DEF_C2H_Message,	
	&asn_DEF_H2C_Message,	
	&asn_DEF_BDM_C2S_Message,	
	&asn_DEF_BDM_S2C_Message,	
	&asn_DEF_BDM_Sync_Metadata_Message,	
	&asn_DEF_BDM_Sync_Datapoints_Message,	
	0
};

