/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_ResourceRecord_H_
#define	_ResourceRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BDMSyncDatapoint;

/* ResourceRecord */
typedef struct ResourceRecord {
	OCTET_STRING_t	 resourceKey;
	struct ResourceRecord__resourceDatapoints {
		A_SEQUENCE_OF(struct BDMSyncDatapoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resourceDatapoints;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BDMSyncDatapoint.h"

#endif	/* _ResourceRecord_H_ */
