/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_ResourceDatapointsQuery_H_
#define	_ResourceDatapointsQuery_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <GeneralizedTime.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResourceDatapointsQuery */
typedef struct ResourceDatapointsQuery {
	PrintableString_t	 habType;
	PrintableString_t	 habId;
	PrintableString_t	 nodeId;
	PrintableString_t	 resourceId;
	GeneralizedTime_t	 datapointStartTime;
	GeneralizedTime_t	 datapointEndTime;
	long	 entryStart;
	long	 entryEnd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceDatapointsQuery_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceDatapointsQuery;

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceDatapointsQuery_H_ */
