/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_ResourceFlavor_H_
#define	_ResourceFlavor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResourceFlavor {
	ResourceFlavor_sensor	= 0,
	ResourceFlavor_actuator	= 1,
	ResourceFlavor_parameter	= 2
} e_ResourceFlavor;

/* ResourceFlavor */
typedef long	 ResourceFlavor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceFlavor;
asn_struct_free_f ResourceFlavor_free;
asn_struct_print_f ResourceFlavor_print;
asn_constr_check_f ResourceFlavor_constraint;
ber_type_decoder_f ResourceFlavor_decode_ber;
der_type_encoder_f ResourceFlavor_encode_der;
xer_type_decoder_f ResourceFlavor_decode_xer;
xer_type_encoder_f ResourceFlavor_encode_xer;
per_type_decoder_f ResourceFlavor_decode_uper;
per_type_encoder_f ResourceFlavor_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceFlavor_H_ */
