/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#ifndef	_StreamDirection_H_
#define	_StreamDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StreamDirection {
	StreamDirection_producer	= 0,
	StreamDirection_consumer	= 1
} e_StreamDirection;

/* StreamDirection */
typedef long	 StreamDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StreamDirection;
asn_struct_free_f StreamDirection_free;
asn_struct_print_f StreamDirection_print;
asn_constr_check_f StreamDirection_constraint;
ber_type_decoder_f StreamDirection_decode_ber;
der_type_encoder_f StreamDirection_encode_der;
xer_type_decoder_f StreamDirection_decode_xer;
xer_type_encoder_f StreamDirection_encode_xer;
per_type_decoder_f StreamDirection_decode_uper;
per_type_encoder_f StreamDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StreamDirection_H_ */
