/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_StreamData_H_
#define	_StreamData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StreamData */
typedef struct StreamData {
	PrintableString_t	 nodeId;
	PrintableString_t	 streamId;
	OCTET_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StreamData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StreamData;

#ifdef __cplusplus
}
#endif

#endif	/* _StreamData_H_ */
