/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol0"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto`
 */

#ifndef	_Stream_H_
#define	_Stream_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include "StreamDirection.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Stream */
typedef struct Stream {
	PrintableString_t	 id;
	PrintableString_t	 type;
	StreamDirection_t	 direction;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Stream_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Stream;

#ifdef __cplusplus
}
#endif

#endif	/* _Stream_H_ */
