/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BionetProtocol1"
 * 	found in "bionet-protocol-0.asn1"
 * 	`asn1c -Werror -fnative-types -fskeletons-copy -pdu=auto -gen-PER`
 */

#ifndef	_Value_H_
#define	_Value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <INTEGER.h>
#include <NativeReal.h>
#include <PrintableString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Value_PR {
	Value_PR_NOTHING,	/* No components present */
	Value_PR_binary_v,
	Value_PR_uint8_v,
	Value_PR_int8_v,
	Value_PR_uint16_v,
	Value_PR_int16_v,
	Value_PR_uint32_v,
	Value_PR_int32_v,
	Value_PR_real,
	Value_PR_string
} Value_PR;

/* Value */
typedef struct Value {
	Value_PR present;
	union Value_u {
		BOOLEAN_t	 binary_v;
		long	 uint8_v;
		long	 int8_v;
		long	 uint16_v;
		long	 int16_v;
		INTEGER_t	 uint32_v;
		long	 int32_v;
		double	 real;
		PrintableString_t	 string;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Value;

#ifdef __cplusplus
}
#endif

#endif	/* _Value_H_ */
