/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'env_general_msg' message type.
 */

#ifndef ENVGENMSG_H
#define ENVGENMSG_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  ENVGENMSG_SIZE = 8,

  /** The Active Message type associated with this message. */
  ENVGENMSG_AM_TYPE = 33,

  /* Field node_id: type uint16_t, offset (bits) 0, size (bits) 16 */
  /** Offset (in bytes) of the field 'node_id' */
  ENVGENMSG_NODE_ID_OFFSET = 0,
  /** Offset (in bits) of the field 'node_id' */
  ENVGENMSG_NODE_ID_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'node_id' */
  ENVGENMSG_NODE_ID_SIZE = 2,
  /** Size (in bits) of the field 'node_id' */
  ENVGENMSG_NODE_ID_SIZEBITS = 16,

  /* Field volt: type uint16_t, offset (bits) 16, size (bits) 16 */
  /** Offset (in bytes) of the field 'volt' */
  ENVGENMSG_VOLT_OFFSET = 2,
  /** Offset (in bits) of the field 'volt' */
  ENVGENMSG_VOLT_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'volt' */
  ENVGENMSG_VOLT_SIZE = 2,
  /** Size (in bits) of the field 'volt' */
  ENVGENMSG_VOLT_SIZEBITS = 16,

  /* Field temp: type uint16_t, offset (bits) 32, size (bits) 16 */
  /** Offset (in bytes) of the field 'temp' */
  ENVGENMSG_TEMP_OFFSET = 4,
  /** Offset (in bits) of the field 'temp' */
  ENVGENMSG_TEMP_OFFSETBITS = 32,
  /** Size (in bytes) of the field 'temp' */
  ENVGENMSG_TEMP_SIZE = 2,
  /** Size (in bits) of the field 'temp' */
  ENVGENMSG_TEMP_SIZEBITS = 16,

  /* Field photo: type uint16_t, offset (bits) 48, size (bits) 16 */
  /** Offset (in bytes) of the field 'photo' */
  ENVGENMSG_PHOTO_OFFSET = 6,
  /** Offset (in bits) of the field 'photo' */
  ENVGENMSG_PHOTO_OFFSETBITS = 48,
  /** Size (in bytes) of the field 'photo' */
  ENVGENMSG_PHOTO_SIZE = 2,
  /** Size (in bits) of the field 'photo' */
  ENVGENMSG_PHOTO_SIZEBITS = 16,
};

/**
 * Return the value of the field 'node_id'
 */
uint16_t ENVGENMSG_node_id_get(tmsg_t *msg);

/**
 * Set the value of the field 'node_id'
 */
void ENVGENMSG_node_id_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'volt'
 */
uint16_t ENVGENMSG_volt_get(tmsg_t *msg);

/**
 * Set the value of the field 'volt'
 */
void ENVGENMSG_volt_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'temp'
 */
uint16_t ENVGENMSG_temp_get(tmsg_t *msg);

/**
 * Set the value of the field 'temp'
 */
void ENVGENMSG_temp_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'photo'
 */
uint16_t ENVGENMSG_photo_get(tmsg_t *msg);

/**
 * Set the value of the field 'photo'
 */
void ENVGENMSG_photo_set(tmsg_t *msg, uint16_t value);

#endif
