
#
# Copyright (C) 2004-2008, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G and NNC06CB40C.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


-include ../../../Makefile.params
include ../../Makefile.params


EXE = cpod-hab


.PHONY: all clean new install


SOURCE_FILES =  \
	available_opcodes.c\
	crcccitt.c         \
	daemonize.c        \
	main.c             \
	pidfile.c          \
	read_next_packet.c \
	reliable_io.c      \
	sampling_parameters.c\
	send_next_packet_streaming.c\
	set_time.c         \
	shake_hands.c      \
	start_streaming.c  \
	next_command_number.c  \
	verify_response.c  \

CFLAGS  := -I../libamedevice -I../libhab -I../../util ${CFLAGS} \
           `pkg-config --cflags glib-2.0 bluez`
LDFLAGS := -L../libhab -L../libamedevice ${LDFLAGS}
LDLIBS = -lhab `pkg-config --libs bluez glib-2.0`


all: $(EXE)


$(EXE): $(SOURCE_FILES:%.c=%.o)
	$(CC) $(CFLAGS) $(LDFLAGS) $(SOURCE_FILES:%.c=%.o) $(LDLIBS) -o $@


$(SOURCE_FILES:%.c=%.o): cpod.h


clean:
	rm -f *.o $(EXE) core

new: clean all


install: $(EXE)
	install -m 755 $(EXE)          $(EXP_BIN_DIR)
	install -m 755 init.d.cpod-hab $(EXP_INIT_DIR)/cpod-hab
	install -m 644 cpod-hab.conf   $(EXP_ETC_DIR)

