#!/bin/sh

case "$1" in

    start)
        echo -n "Starting bdmplot: "
        bdmplot --default-bdm-id $(hostname) &
        # sleep for a while here so that it can initialize and be ready to publish to any subscribers
        sleep 1
        echo ok
        ;;

    stop)
        echo -n "Stopping bdmplot: "
        kill `pidof -x bdmplot`
        echo ok
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1

esac

exit 0
