
export TARGET_OS ?= LINUX


CAL_DIR=../../../cal

CAL_PD_MODULES =   \
    dnssd   \
    bdp     \


CC = gcc
CFLAGS = -Werror -Wall -O2 -I${CAL_DIR} `pkg-config --cflags glib-2.0`

LDLIBS = -lpthread `pkg-config --libs glib-2.0`

ifeq (${TARGET_OS},LINUX)
    dnssd_LDLIBS = `pkg-config --libs avahi-compat-libdns_sd`
endif

