#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#

export TARGET_OS ?= LINUX


CAL_DIR=../../../cal

CAL_PD_MODULES =   \
    dnssd   \
    bdp     \


CC = gcc
CFLAGS = -Werror -Wall -O2 -I${CAL_DIR} `pkg-config --cflags glib-2.0`

LDLIBS = -lpthread `pkg-config --libs glib-2.0`

ifeq (${TARGET_OS},LINUX)
    dnssd_LDLIBS = `pkg-config --libs avahi-compat-libdns_sd`
endif

