#
# Copyright (C) 2008-2009, Regents of the University of Colorado.
#

SENSORBOARD=mts300
PFLAGS += -I%T/lib/net/ctp -I%T/lib/net -I%T/lib/net/4bitle -I%T/lib/net/drip
COMPONENT=MmodNodeAppC
include $(MAKERULES)

