
include ../Makefile.params

CFLAGS += -I ..

OBJS =                          \
    event-new.o                 \
    event-free.o                \
    peer-new.o                  \
    peer-address.o              \
    peer-free.o                 \


all: $(OBJS)

clean:
	rm -f $(OBJS)

test:

install:

.PHONY: all test install clean

