
include ../Makefile.params

CFLAGS += -I ..

OBJS =                          \
    free-event.o                \
    free-peer.o                 \


all: $(OBJS)

clean:
	rm -f $(OBJS)

test:

install:

.PHONY: all test install clean

