#!/bin/bash
#
# Copyright (c) 2008-2009, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


function usage {
    echo "audio-stream-consumer"
    echo ""
    echo "Connects to a Bionet audio Stream producer and plays it out the speakers."
    echo "usage: audio-stream-consumer STREAM"
    echo ""
}


BSTREAM="./bionet-stream"


STREAM="$1"
if [ -z "$STREAM" ]; then
    echo "no stream name specified, pick one:"
    $BSTREAM 
    echo
    usage
    exit 1
fi


# for sox
BIOSERVE_AUDIO_FORMAT_SOX="-t raw -r 9600 -c 1 -s -w"


# for aplay
BIOSERVE_AUDIO_FORMAT_APLAY="-t raw -r 9600 -c 1 -f S16_LE"




# save via sox
#$BSTREAM --nag $NAG "$1" | sox $BIOSERVE_AUDIO_FORMAT_SOX - "$2"


# play via aplay
$BSTREAM "$STREAM" | aplay $BIOSERVE_AUDIO_FORMAT_APLAY

