#!/bin/bash
#
# Copyright (C) 2008-2009, Regents of the University of Colorado.
#


function usage {
    echo "audio-stream-consumer"
    echo "Connects to a Bionet audio Stream producer and plays it out the speakers."
    echo "usage: audio-stream-consumer OPTIONS STREAM"
    echo ""
    echo "OPTIONS:"
    echo "    --nag NAG-HOSTNAME"
    echo ""
}


BSTREAM="../../client/stream/bionet-stream"


if [ -z "$BIONET_NAG" ]; then
    BIONET_NAG="bionet.colorado.edu"
fi

if [ "$1" = "--nag" ]; then
    shift
    BIONET_NAG="$1"
    shift
fi

STREAM="$1"
if [ -z "$STREAM" ]; then
    echo "no stream name specified, pick one:\n"
    $BSTREAM --nag $BIONET_NAG
    echo
    usage
    exit 1
fi


# for sox
BIOSERVE_AUDIO_FORMAT_SOX="-t raw -r 9600 -c 1 -s -w"


# for aplay
BIOSERVE_AUDIO_FORMAT_APLAY="-t raw -r 9600 -c 1 -f S16_LE"




# save via sox
#$BSTREAM --nag $NAG "$1" | sox $BIOSERVE_AUDIO_FORMAT_SOX - "$2"


# play via aplay
$BSTREAM --nag $BIONET_NAG "$1" | aplay -D plug:dmix $BIOSERVE_AUDIO_FORMAT_APLAY

