#!/bin/bash
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


function usage {
    echo "audio-stream-producer"
    echo ""
    echo "Sends an audio file to a Bionet audio Stream consumer."
    echo "usage: audio-stream-producer SOUND-FILE STREAM"
    echo ""
}


# for sox
BIOSERVE_AUDIO_FORMAT="-t raw -r 9600 -c 1 -s -w"

BSTREAM="./bionet-stream"


SOUND_FILE="$1"
shift
if [ -z "$SOUND_FILE" ]; then 
    echo "no sound file specified!"
    echo 
    usage
    exit 1
fi

IN_TYPE=$(file "$SOUND_FILE") 


STREAM=$1
shift
if [ -z "$STREAM" ]; then 
    echo "no target stream specified, pick one:"
    $BSTREAM
fi


if echo $IN_TYPE | egrep -q '(WAVE audio)|(Sun/NeXT audio data)'; then
    sox "$SOUND_FILE" $BIOSERVE_AUDIO_FORMAT - | $BSTREAM "$STREAM"

elif echo $IN_TYPE | egrep -q '(MPEG.*layer III)|(MP3)'; then
    mpg123 --au - "$SOUND_FILE" | sox -t au - $BIOSERVE_AUDIO_FORMAT - | $BSTREAM "$STREAM"

else
    echo "unknown sound file format: $IN_TYPE"
fi


