/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'mmod_accel_msg' message type.
 */

#ifndef MMODACCELMSG_H
#define MMODACCELMSG_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  MMODACCELMSG_SIZE = 6,

  /** The Active Message type associated with this message. */
  MMODACCELMSG_AM_TYPE = 34,

  /* Field node_id: type uint16_t, offset (bits) 0, size (bits) 16 */
  /** Offset (in bytes) of the field 'node_id' */
  MMODACCELMSG_NODE_ID_OFFSET = 0,
  /** Offset (in bits) of the field 'node_id' */
  MMODACCELMSG_NODE_ID_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'node_id' */
  MMODACCELMSG_NODE_ID_SIZE = 2,
  /** Size (in bits) of the field 'node_id' */
  MMODACCELMSG_NODE_ID_SIZEBITS = 16,

  /* Field accel_x: type uint16_t, offset (bits) 16, size (bits) 16 */
  /** Offset (in bytes) of the field 'accel_x' */
  MMODACCELMSG_ACCEL_X_OFFSET = 2,
  /** Offset (in bits) of the field 'accel_x' */
  MMODACCELMSG_ACCEL_X_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'accel_x' */
  MMODACCELMSG_ACCEL_X_SIZE = 2,
  /** Size (in bits) of the field 'accel_x' */
  MMODACCELMSG_ACCEL_X_SIZEBITS = 16,

  /* Field accel_y: type uint16_t, offset (bits) 32, size (bits) 16 */
  /** Offset (in bytes) of the field 'accel_y' */
  MMODACCELMSG_ACCEL_Y_OFFSET = 4,
  /** Offset (in bits) of the field 'accel_y' */
  MMODACCELMSG_ACCEL_Y_OFFSETBITS = 32,
  /** Size (in bytes) of the field 'accel_y' */
  MMODACCELMSG_ACCEL_Y_SIZE = 2,
  /** Size (in bits) of the field 'accel_y' */
  MMODACCELMSG_ACCEL_Y_SIZEBITS = 16,
};

/**
 * Return the value of the field 'node_id'
 */
uint16_t MMODACCELMSG_node_id_get(tmsg_t *msg);

/**
 * Set the value of the field 'node_id'
 */
void MMODACCELMSG_node_id_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'accel_x'
 */
uint16_t MMODACCELMSG_accel_x_get(tmsg_t *msg);

/**
 * Set the value of the field 'accel_x'
 */
void MMODACCELMSG_accel_x_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'accel_y'
 */
uint16_t MMODACCELMSG_accel_y_get(tmsg_t *msg);

/**
 * Set the value of the field 'accel_y'
 */
void MMODACCELMSG_accel_y_set(tmsg_t *msg, uint16_t value);

#endif
