/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'mmod_accel_msg' message type. See mmodaccelmsg.h for more details.
 */

#include <message.h>
#include "mmodaccelmsg.h"

uint16_t MMODACCELMSG_node_id_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void MMODACCELMSG_node_id_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t MMODACCELMSG_accel_x_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void MMODACCELMSG_accel_x_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint16_t MMODACCELMSG_accel_y_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 16);
}

void MMODACCELMSG_accel_y_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 32, 16, value);
}

