#!/bin/bash

UNIQUE=$$

if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

if [ -z "$TEST_DURATION" ]; then
    TEST_DURATION=30
fi

echo starting bionet-watcher under valgrind memcheck
libtool --mode=execute valgrind --suppressions=valgrind.suppressions --quiet --log-file=out.valgrind.watcher --num-callers=25 --tool=memcheck --trace-children=yes --leak-check=full $ROOT/client/watcher/bionet-watcher --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" >| out.watcher &

sleep 2  # let the client come up before starting the hab (valgrind makes it slow)


echo starting random-hab
$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bionet-watcher --max-delay 1 >| out.random-hab &


sleep $TEST_DURATION


echo "killing the HAB"
kill %2
wait %2

sleep 4  # to let the clients notice


echo "killing the bionet-watcher (under valgrind)"
kill %1
wait %1


if ! diff -q out.watcher out.random-hab; then
    echo "ERROR: watcher output differs from random-hab output:"
    diff -u out.random-hab out.watcher
    exit 1
fi
echo "watcher output is identical to random-hab output, yay"

if [ $(wc -l < out.valgrind.watcher) -gt 0 ]; then
    echo "valgrind memcheck output:"
    cat out.valgrind.watcher
    exit 1
fi

echo "valgrind memcheck finds no errors :-)"
exit 0

