#!/bin/sh

case "$1" in

    start)
        echo -n "Starting bdmplot: "
        bdmplot-cacher &
        # sleep for a while here so that it can initialize and be ready to publish to any subscribers
        sleep 1
        echo ok
        ;;

    stop)
        echo -n "Stopping bdmplot: "
        kill `pidof -x bdmplot-cacher`
        echo ok
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1

esac

exit 0
