#!/bin/bash
#
# Copyright (c) 2008-2010, Regents of the University of Colorado.
# This work was supported by NASA contracts NNJ05HE10G, NNC06CB40C, and
# NNC07CB47C.
#


UNIQUE=$$

RETVAL=0

YEAR=`date +%Y`
PREV_YEAR=$(($YEAR-1))
NEXT_YEAR=$(($YEAR+1))


if [ -z "$ROOT" ]; then
    echo "ROOT environment variable is undefined"
    exit 1
fi

if [ -z "$TEST_DURATION" ]; then
    TEST_DURATION=30
fi

. $ROOT/test/config.sh
. $ROOT/test/testlib.sh

echo "making DB file"
rm -f bdm.db
sqlite3 bdm.db < $ROOT/data-manager/server/schema || exit 1

export G_SLICE=always-malloc 
export G_DEBUG=gc-friendly,resident-modules 

echo starting BDM
$ROOT/data-manager/server/bionet-data-manager -x bdm.ini.test --habs "random-hab.$UNIQUE" --nodes "random-hab.$UNIQUE.*" --resources "random-hab.$UNIQUE.*:*" &
BDMPID=$!

echo starting bionet-watcher
$ROOT/client/watcher/bionet-watcher -T "$PREV_YEAR-01-01 00:00:00" -t "$NEXT_YEAR-12-31 12:59:59" -r "random-hab.$UNIQUE.*:*" -h "random-hab.$UNIQUE" -n "random-hab.$UNIQUE.*" >| out.watcher &
WATCHPID=$!

sleep 3 # let the bdm come up before starting the HAB

echo starting random-hab
$ROOT/hab/random/random-hab --id $UNIQUE --output-mode bionet-watcher --max-delay 1 >| out.random-hab &
HABPID=$!

sleep $TEST_DURATION


echo "test run complete, killing random-hab"
kill $HABPID
wait $HABPID
sleep 20 # let the BDM get any last things sent by the random-hab


echo "killing BDM"
kill $BDMPID
wait $BDMPID

echo "killing bionet-watcher"
kill $WATCHPID
wait $WATCHPID
sleep 1

sort -u out.random-hab > out.random-hab-sorted
grep -v "no known value" out.random-hab-sorted | grep -v "    Resources:" | grep -v "new node: " | grep -v "lost node:" | grep -v "lost hab:" | grep -v "new node:" | grep -v "new hab:" | grep -v "        Binary " | grep -v "        Double " | grep -v "        Float " | grep -v "        Int" | grep -v "        UInt" | grep -v "        String " > out.random


for log in out.watcher; do
    sort -u $log > $log.sorted
    grep -v "BDM" $log.sorted > out.bionet
    grep "BDM" $log.sorted | sed 's/BDM //' | grep -v "no known value" | grep -v "    Resources:" | grep -v "new node: " > out.bdm
    if ! diff -q out.random-hab-sorted out.bionet; then
	echo "ERROR: bionet output differs from random-hab output:"
	diff -u out.random-hab-sorted out.bionet
	RETVAL=1
    fi

    if ! diff -q out.random out.bdm; then
	echo "ERROR: bdm output differs from random-hab output:"
	diff -u out.random out.bdm
	RETVAL=1
    fi
done

exit $RETVAL
